[tools]
go = "1.24"

[env]
_.path = ["{{config_root}}/bin"]

[tasks.test]
run = "go test ./..."

[tasks.iptv]
run = "go run ./cmd/iptv"
env = { _.file = ".env" }

[tasks.build]
run = "go build -o bin/iptv ./cmd/iptv"
